Document: ntcore
Title: Debian ntcore Manual
Author: <insert document author here>
Abstract: This manual describes what ntcore is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ntcore/ntcore.sgml.gz

Format: postscript
Files: /usr/share/doc/ntcore/ntcore.ps.gz

Format: text
Files: /usr/share/doc/ntcore/ntcore.text.gz

Format: HTML
Index: /usr/share/doc/ntcore/html/index.html
Files: /usr/share/doc/ntcore/html/*.html
